# Generated by Django 4.2.23 on 2025-06-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_interviewee', '0005_userprofileskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='career_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(through='ai_interviewee.UserProfileSkill', to='ai_interviewee.skill'),
        ),
    ]
